perspectivesx_project/perspectivesx/urls.py
from django.conf.urls import url

from perspectivesx.views import add_activity, index, student_submission, create_template, curate_item, LTIindex, LTInot_authorized, \
    UserSubmissionItemList, UserCuratedItemList, PerspectiveList, display_perspective_items, \
    GetSubmissionScore, LTItest, studentview

urlpatterns = [
                  url(r'^LTItest/$', LTItest, name='LTItest'),
                  url(r'^LTI/$', LTIindex, name='LTIindex'),
                  url(r'^studentview/(?P<resource_link_id>[\w\-\.]+)/$', studentview, name='studentview'),
                  url(r'^add_activity/(?P<resource_link_id>[\w\-\.]+)/$', add_activity, name='add_activity'),
                  url(r'^$', index, name='index'),
                  url(r'^get_user_submission_items/(?P<activity>\d+)/(?P<perspective>\d+)/(?P<username>[\w\-\.\:]+)/$',
                      UserSubmissionItemList.as_view(),
                      name="REST_user_sub_items"),
                  url(r'^display_perspective_items/(?P<activity>\d+)/(?P<perspective>\d+)/(?P<resource_link_id>[\w\-\.]+)/$', display_perspective_items,
                      name="display_perspective_items"),
                  url(r'^get_user_curated_items/(?P<activity>\d+)/(?P<perspective>\d+)/(?P<username>[\w\-\.\:]+)/$',
                      UserCuratedItemList.as_view(),
                      name="REST_user_cur_items"),
                  url(r'^get_template_items/(?P<activity>\d+)/$', PerspectiveList.as_view(),
                      name="REST_template_items"),
                  url(r'^LTI/$', LTIindex, name='LTIindex'),
                  url(r'^not_authorized', LTInot_authorized, name='LTInot_authorized'),
                  url(r'^submission/(?P<resource_link_id>[\w\-\.]+)/(?P<activity_id>\d+)/$', student_submission, name='submission'),
                  url(r'^submission/(?P<resource_link_id>[\w\-\.]+)/(?P<activity_id>\d+)/(?P<perspective>\d+)/$', student_submission,
                      name="Defined submission"),
                  url(r'^create_template/(?P<resource_link_id>[\w\-\.]+)$', create_template, name='create_template'),
                  url(r'^curate/(?P<activity_name_slug>[\w\-]+)/$', curate_item, name="Item Curator"),
                  url(r'^curate/(?P<activity_name_slug>[\w\-]+)/(?P<item>\d+)/$', curate_item,
                      name="Defined Item Curator"),
                  url(r'GetSubmissionScore/(?P<userid>\d+)/(?P<activity>\d+)/$', GetSubmissionScore.as_view(),
                      name="get_submission"), ]

perspectivesx_project/perspectivesx_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

#app_name="perspectivesx"

urlpatterns = [
    # Examples:
    # url(r'^$', 'perspectivesx_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^perspectivesX/',include('perspectivesx.urls')),
    url(r'^api/', include('perspectivesx.apiurls'))

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

perspectivesx_project/perspectivesx/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, HTML, Field, Row,Hidden
from crispy_forms.bootstrap import FormActions,InlineRadios,PrependedText, InlineField,StrictButton
from perspectivesx.models import Template, TemplateItem, Activity, LearnerPerspectiveSubmission,LearnerSubmissionItem,User,CuratedItem
from perspectivesx.formsetlayout import Formset as FormSetLayout

class ActivityForm(forms.ModelForm):

    title = forms.CharField(max_length = 5000, label= "Title:")
    description = forms.CharField(label = "Decription:", widget= forms.Textarea)

    perspective_terminology = forms.CharField(max_length = 1000, label= "Perspective Terminology:")
    item_terminology = forms.CharField(max_length = 1000, label= "Item Terminology:")

    template = forms.ModelChoiceField(queryset = Template.objects.all() ,label= "Choose activity template:")

    SELECTED = 'Allow learners to choose a perspective'
    RANDOM = 'Randomly assign a perspective for learner'
    ALL = 'Allow Learners to contribute to all perspectives'
    PERSPECTIVE_SELECTION_OPTIONS = (
        (SELECTED, SELECTED),
        (RANDOM, RANDOM),
        (ALL, ALL)
    )
    perspective_selection = forms.ChoiceField(choices = PERSPECTIVE_SELECTION_OPTIONS, label= "Learner Contribution:",
                                             widget= forms.RadioSelect)

    '''
    SELECTED = 'Allow learners to choose a perspective to curate'
    RANDOM = 'Randomly assign a perspective that learners have not attempted for curation'
    ALL = 'Allow Learners to curate all perspectives'
    PERSPECTIVE_CURATION_OPTIONS = (
        (SELECTED, SELECTED),
        (RANDOM, RANDOM),
        (ALL, ALL)
    )
    enable_curation = forms.ChoiceField(choices=PERSPECTIVE_CURATION_OPTIONS, label= "Learner Curation:",
                                         widget= forms.RadioSelect)

    ENABLE = 'Enable Search'
    SUMMARIZE = 'Use Topic Models to summarise learner submissions'
    VIEW = 'Allow learners to view the knowledge base before making a submission'
    KB_SETTINGS_OPTIONS = (
        (ENABLE, ENABLE),
        (SUMMARIZE, SUMMARIZE),
        (VIEW, VIEW)
    )
    kb_setting = forms.ChoiceField(choices =KB_SETTINGS_OPTIONS, label= "Knowledge Base Setting:",
                                   widget=forms.RadioSelect)
    '''

    view_knowledge_base_before_sumbmission = forms.BooleanField(label ="Allow learners to view Knowledge base before submission", initial = False)
    enable_search = forms.BooleanField(label ="Enable search", initial = False)

    contribution_score = forms.IntegerField(label ="Contribution Score", initial = 50)
    curation_score = forms.IntegerField(label= "Curation Score", initial = 50)
    minimum_contributions = forms.IntegerField(label= "Minimum Number of Contributions", initial = 3 )
    minimum_curations = forms.IntegerField(label = "Minimum Number of Curated Responses", initial = 3)

    def __init__(self, *args, **kwargs):
        resource_link_id = "-"
        if 'resource_link_id' in kwargs:
            resource_link_id = kwargs.pop('resource_link_id')
        super(ActivityForm, self).__init__(*args, **kwargs)
        activity_id = "-"
        if 'instance' in kwargs:
            activity = kwargs['instance']
            activity_id = activity.id
            #print(activity_id)

        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_action = '/perspectivesX/add_activity/'+resource_link_id+'/'
        self.helper.form_class = "form-horizontal"
        self.helper.field_class ='col-sm-10'
        self.helper.label_class = 'control-label col-sm-2'
        self.helper.layout = Layout(
            HTML('<div class="form-group"><label class="control-label control-label col-sm-2">Activity ID:</label><div class="controls col-sm-10">' + str(activity_id) + '</div></div>'),
            Fieldset(
            "",'title','description','template',
            FormActions(
                HTML("OR &emsp; "),
                StrictButton("Create Custom Template", name="create template",
                            value="create template",css_class= 'create-template')),
           'perspective_selection','view_knowledge_base_before_sumbmission','enable_search','perspective_terminology', 'item_terminology',
            PrependedText('contribution_score', '%', active=True),
            PrependedText('curation_score','%',active= True),'minimum_contributions','minimum_curations'
             ),
            FormActions(
                Submit('Save', 'Save')
            )
        )

    class Meta:
        #associate activity Form with an Activity
        model = Activity
        fields= ('title','description','perspective_terminology', 'item_terminology', 'template','perspective_selection','view_knowledge_base_before_sumbmission','enable_search',
                 'contribution_score','curation_score','minimum_contributions','minimum_curations')

class LearnerSubmissionItemForm(forms.ModelForm):
    #Item stores the learner's contribution (entry) for this Item
    item = forms.CharField(label="")
    #Position stores the position of the item (index of the contribution)
    position = forms.IntegerField(widget = forms.HiddenInput, required = False)
    #learner_submission maps the item to the relevant learner submission
    learner_submission = forms.ModelChoiceField(queryset = LearnerPerspectiveSubmission.objects.all(),
                                                widget = forms.HiddenInput, required = False)

    def __init__(self,*args,**kwargs):
        super(LearnerSubmissionItemForm, self).__init__(*args, **kwargs)
        #Define form helper
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.layout = Layout(
            Fieldset('','item','position','learner_submission'))

    class Meta:
        model = LearnerSubmissionItem
        fields = ('item','position','learner_submission')

class AddLearnerSubmissionItemForm(forms.ModelForm):
    # Item stores the learner's contribution (entry) for this Item
    item = forms.CharField(label="")
    # Position stores the position of the item (index of the contribution)
    position = forms.IntegerField(widget=forms.HiddenInput, required=False)
    # learner_submission maps the item to the relevant learner submission
    learner_submission = forms.ModelChoiceField(queryset=LearnerPerspectiveSubmission.objects.all(),
                                                widget=forms.HiddenInput, required=False)

    def __init__(self, *args, **kwargs):
        super(AddLearnerSubmissionItemForm, self).__init__(*args, **kwargs)
        # Define form helper
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.layout = Layout(
            Fieldset('Enter Item', 'item', 'position', 'learner_submission'),  FormActions(
                Submit('Submit', 'Submit')
            ))

    class Meta:
        model = LearnerSubmissionItem
        fields = ('item', 'position', 'learner_submission')

class LearnerForm(forms.ModelForm):
    #perspective_selection stores the perspective choosen by the learner
    selected_perspective = forms.ModelChoiceField(queryset=[])

    NOSHARE = "Don't Share"
    ANON = 'Share Anonymously'
    SHARE = 'Share with other learners'
    SHARE_OPTIONS = (
        (SHARE, SHARE),
        (ANON, ANON),
        (NOSHARE, NOSHARE),
    )
    #sharing stores the share mode selected by the user
    sharing = forms.ChoiceField(choices = SHARE_OPTIONS ,label = 'Privacy Settings', initial="Share with other learners")
    #activity maps the submission to the undertaken activity
    activity = forms.ModelChoiceField(queryset=Activity.objects.all(),widget = forms.HiddenInput)
    #maps the submission to a particular user; TO BE UPDATED WITH LTI INFO
    created_by = forms.ModelChoiceField(queryset = User.objects.all(), widget = forms.HiddenInput)

    def __init__(self,*args, **kwargs):

        #retrive args from kwargs array
        # self.template_name = kwargs.pop('template_name')
        self.activity = kwargs.pop('activity')
        self.user = kwargs.pop('user')
        self.perspective = kwargs.pop('perspective')
        # call super.__init__()
        super(LearnerForm, self).__init__(*args, **kwargs)

        #set the hidden field values with given parameters
        self.fields['selected_perspective']  = forms.ModelChoiceField(queryset=TemplateItem.objects.filter(
            id = self.perspective), initial = self.perspective, widget = forms.HiddenInput, empty_label= None)

        self.fields['activity'].initial = self.activity
        self.fields['created_by'].initial = User.objects.get(username = self.user)

        #define form helper
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_class = "form-horizontal"
        self.helper.field_class = 'col-sm-10'
        self.helper.label_class = 'control-label col-sm-2'

        #get selected perspective title
        selected_perspective = TemplateItem.objects.get(id = self.perspective).name
        #define form layout

        self.helper.layout = Layout(

            Fieldset('Your initial contributions:',
               HTML("<strong>Please submit items for:</strong> " + selected_perspective),
               InlineRadios('selected_perspective'),FormSetLayout('formset',header = "Add signposts:"),InlineRadios('sharing'),
                     'activity','created_by'
            ),
            FormActions(
                Submit('Submit', 'Submit'),
            )
        )

    class Meta:
        model = LearnerPerspectiveSubmission
        fields = ('selected_perspective','sharing','activity','created_by')

class TemplateItemForm(forms.ModelForm):
    name = forms.CharField(max_length= 500, label = 'Name:', initial = "Perspective/Dimension Name")

perspectivesx_project/templates/Item_curator.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
{% load staticfiles %}


<html lang="en">
  <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Item Curation</title>
      <meta name="author" content="Marco Lindley">
      <link href="{% static "css/bootstrap.min.css" %}" rel = "stylesheet">
      <link href="{% static "css/style.css" %}" rel="stylesheet">
      <script type = "text/javascript" src="{% static "js/jquery.min.js" %}"></script>
      <script type = "text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
      <script type = "text/javascript" src="{%  static "js/scripts.js"%}"></script>
  </head>
  <body>
    <div class="container-fluid">
			<h3>
				PerspectivesX: Curate Item
			</h3>
        <div class = "well well-lg">
            <legend>Perspective to Curate</legend>
            {{ item }}
        </div>
        <div class="well well-lg">
            {% crispy form %}
        </div>
	</div>
</div>
  </body>
</html>

perspectivesx_project/templates/LTIindex.html
<html><head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>LTI</title>
    </head>
    <body>
        <form id="lti-6d5136ce15d24ff8a3051380678b58ab" action="http://127.0.0.1:8000/perspectivesX/LTI/" method="post" enctype="application/x-www-form-urlencoded" style="display:none;">

                <input name="custom_component_display_name" value="XBlock LTI Test">
                <input name="lti_version" value="LTI-1p0">
                <input name="oauth_nonce" value="173164831866740263851500526817">
                <input name="resource_link_id" value="edge.edx.org-6d5136ce15d24ff8a3051380678b58ab">
                <input name="context_id" value="course-v1:UQx+UQx002+2015August">
                <input name="oauth_signature_method" value="HMAC-SHA1">
                <input name="oauth_version" value="1.0">
                <input name="oauth_signature" value="n4ZHXHmIeIKuXvVoVQQutlDyEtA=">
                <input name="lti_message_type" value="basic-lti-launch-request">
                <input name="launch_presentation_return_url" value="">
                <input name="user_id" value="a0d05d435d1a7bbf1e90f99400750bc5">
                <input name="roles" value="Instructor">
                <input name="oauth_consumer_key" value="xblocklti">
                <input name="lis_result_sourcedid" value="course-v1%3AUQx%2BUQx002%2B2015August:edge.edx.org-6d5136ce15d24ff8a3051380678b58ab:a0d05d435d1a7bbf1e90f99400750bc5">
                <input name="launch_presentation_locale" value="en">
                <input name="oauth_timestamp" value="1500526817 ">
                <input name="oauth_callback" value="about:blank">

            <input type="submit" value="Press to Launch">
        </form>
        <script type="text/javascript">
            (function (d) {
                var element = d.getElementById("lti-6d5136ce15d24ff8a3051380678b58ab");
                if (element) {
                    element.submit();
                }
            }(document));
        </script></body></html>

perspectivesx_project/templates/LTItest.html
<html><head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>LTI</title>
    </head>
    <body>
        <form id="lti-6d5136ce15d24ff8a3051380678b58ab" action="http://127.0.0.1:8888/perspectivesX/LTI/" method="post" enctype="application/x-www-form-urlencoded" style="display:none;">

                <input name="custom_component_display_name" value="XBlock LTI Test">
                <input name="lti_version" value="LTI-1p0">
                <input name="oauth_nonce" value="173164831866740263851500526817">
                <input name="resource_link_id" value="edge.edx.org-6d5136ce15d24ff8a3051380678b58ab">
                <input name="context_id" value="course-v1:UQx+UQx002+2015August">
                <input name="oauth_signature_method" value="HMAC-SHA1">
                <input name="oauth_version" value="1.0">
                <input name="oauth_signature" value="n4ZHXHmIeIKuXvVoVQQutlDyEtA=">
                <input name="lti_message_type" value="basic-lti-launch-request">
                <input name="launch_presentation_return_url" value="">
                <input name="user_id" value="a0d05d435d1a7bbf1e90f99400750bc5dddeeekkfrereredddaaa">
                <input name="roles" value="Instructor">
                <input name="oauth_consumer_key" value="perspectivesxlti">
                <input name="lis_result_sourcedid" value="course-v1%3AUQx%2BUQx002%2B2015August:edge.edx.org-6d5136ce15d24ff8a3051380678b58ab:a0d05d435d1a7bbf1e90f99400750bc5">
                <input name="launch_presentation_locale" value="en">
                <input name="oauth_timestamp" value="1500526817 ">
                <input name="oauth_callback" value="about:blank">
                <input name="custom_activity_id" value="10">
            <input type="submit" value="Press to Launch">
        </form>
        <script type="text/javascript">
            (function (d) {
                var element = d.getElementById("lti-6d5136ce15d24ff8a3051380678b58ab");
                if (element) {
                    element.submit();
                }
            }(document));
        </script></body></html>

perspectivesx_project/templates/add_activity.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
{% load staticfiles %}


<html lang="en">
  <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Add Activity</title>
      <meta name="author" content="Marco Lindley">
      <link href="{% static "css/bootstrap.min.css" %}" rel = "stylesheet">
      <link href="{% static "css/style.css" %}" rel="stylesheet">
      <script type = "text/javascript" src="{% static "js/jquery.min.js" %}"></script>
      <script type = "text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
      <script type = "text/javascript" src="{%  static "js/scripts.js"%}"></script>

      <style>
        li:nth-child(odd) { background: none; }
      </style>
  </head>
  <body>
    <div class="container-fluid">
			<h3>
				PerspectivesX: Add/Edit Activity
			</h3>
        <div class="well well-lg">
          {% include "roleswitch.html" with resource_link_id=resource_link_id role=role display_view=display_view allowed_admin_roles=allowed_admin_roles %}
          {% crispy form %}
        </div>
        <script>
        $("button.btn.create-template").click(function(){
            window.location.href = "/perspectivesX/create_template/{{resource_link_id}}";
        });
        $("#id_curation_score").change(function(){
            contribution_score  = 100-parseInt(document.getElementById('id_curation_score').value)
            document.getElementById('id_contribution_score').value = contribution_score

        });
         $("#id_contribution_score").change(function(){
            curation_score  = 100-parseInt(document.getElementById('id_contribution_score').value)
            document.getElementById('id_curation_score').value = curation_score
        });
        </script>
	</div>
</div>
  </body>
</html>

perspectivesx_project/templates/add_item.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>PerspectiveX: Add Item</title>

    <meta name="description" content="Source code generated using layoutit.com">
    <meta name="author" content="Marco Lindley">
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/style.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="http://getbootstrap.com.vn/examples/equal-height-columns/equal-height-columns.css" />
    <script type="text/javascript" src="{% static "js/jquery.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/scripts.js" %}"></script>

</head>
<body>

<div class="container-fluid">
    <div class=jumbotron align="center">
        <h2>
            PerspectivesX: The world through your eyes
        </h2>
    </div>
        <div class = "well">
            <h3>Add Item to {{ submission }}</h3>
            {% crispy form %}
        </div>


</div>


</body>
</html>

perspectivesx_project/templates/choose_item.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
{% load staticfiles %}


<html lang="en">
  <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Item Curation</title>
      <meta name="author" content="Marco Lindley">
      <link href="{% static "css/bootstrap.min.css" %}" rel = "stylesheet">
      <link href="{% static "css/style.css" %}" rel="stylesheet">
      <script type = "text/javascript" src="{% static "js/jquery.min.js" %}"></script>
      <script type = "text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
      <script type = "text/javascript" src="{%  static "js/scripts.js"%}"></script>
  </head>
  <body>
    <div class="container-fluid">
			<!--<h3>
				Choose a Scenario
			</h3>-->
        <div class="well well-lg">
            {% crispy form %}
        </div>
	</div>
</div>
  </body>
</html>

perspectivesx_project/templates/create_template.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
{% load staticfiles %}


<html lang="en">
  <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="author" content="Marco Lindley">
      <link href="{% static "css/bootstrap.min.css" %}" rel = "stylesheet">
      <link href="{% static "css/style.css" %}" rel="stylesheet">
      <title>Template Creator</title>
  </head>
  <body>
    <div class="container-fluid">
			<h3>
				PerspecitvesX: Add Multi-Perspective Template
			</h3>
        <div class="well well-lg">
            {% crispy form %}
        </div>
    </div>
    <script type = "text/javascript" src="{% static "js/jquery.min.js" %}"></script>
    <script type = "text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
    <script type = "text/javascript" src="{%  static "js/scripts.js"%}"></script>
  </body>
</html>

perspectivesx_project/templates/delete_item.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>PerspectiveX</title>

    <meta name="description" content="Source code generated using layoutit.com">
    <meta name="author" content="Marco Lindley">
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/style.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="http://getbootstrap.com.vn/examples/equal-height-columns/equal-height-columns.css" />
    <script type="text/javascript" src="{% static "js/jquery.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/scripts.js" %}"></script>

</head>
<body>

<div class="container-fluid">
    <div class=jumbotron align="center">
        <h2>
            PerspectivesX: The world through your eyes
        </h2>
    </div>
        <div class = "well">
            <div class = "alert-danger">
                <p style = "margin-left:15px; margin-right:15px"> You are about to delete: {{ item }}<br> This could impact your grade ! </p>
                <br>
                <p style = "margin-left:15px">Item: </p>{{ item.item }}
            </div>
        </div>

        <div class = "well">
            {% crispy form %}
        </div>


</div>


</body>
</html>

perspectivesx_project/templates/delete_success.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>PerspectiveX</title>

    <meta name="description" content="Source code generated using layoutit.com">
    <meta name="author" content="Marco Lindley">
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/style.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="http://getbootstrap.com.vn/examples/equal-height-columns/equal-height-columns.css" />
    <script type="text/javascript" src="{% static "js/jquery.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/scripts.js" %}"></script>

</head>
<body>

<div class="container-fluid">
    <div class=jumbotron align="center">
        <h2>
            PerspectivesX: The world through your eyes
        </h2>
    </div>
        <div class = "well">
            <div class = "alert-info">
                <p style = "margin-left:15px; margin-right:15px"> Item Successfully deleted </p>
                <p> Updated score: {{ score }}</p>
            </div>
            <a href = "{% url 'index' %}" class = "btn btn-primary btn-md">Continue</a>
        </div>


</div>


</body>
</html>

perspectivesx_project/templates/formset.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
{% load staticfiles %}
<script type = "text/javascript" src="{% static "js/jquery.min.js" %}"></script>
<script type = "text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
<script type = "text/javascript" src="{%  static "js/scripts.js"%}"></script>
<div class = "alert alert-info">
    <div class="formset">
        <strong>{{ header }}</strong>
        <br>
        <br>
        {%  if item %}
        <input type="submit" , name = "action" value="Add new {{ item }}" class="btn btn-info">
              <span class="glyphicon glyphicon-plus"></span>
        </input>
        {% endif %}

        <input type="hidden" name="extra" value="{{extra}}">
        <br/>
        <br/>
        {% if helper %}
            {% crispy formset %}
        {% else %}
            {{ formset|crispy }}
        {% endif %}
    </div>
</div>

perspectivesx_project/templates/learner_submission.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
{% load staticfiles %}


<html lang="en">
  <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Learner Submission</title>
      <meta name="author" content="Marco Lindley">
      <link href="{% static "css/bootstrap.min.css" %}" rel = "stylesheet">
      <link href="{% static "css/style.css" %}" rel="stylesheet">
      <style>
        li:nth-child(odd) { background: none; }
      </style>
      <title>{% block title_block %}{% endblock %}</title>
  </head>
  <body>
    <div class="container-fluid">
			<!--<h3>
				{{ activity_name }}
			</h3>-->
        <div class="well well-lg">
            {% crispy form %}
        </div>
    </div>
    <script type = "text/javascript" src="{% static "js/jquery.min.js" %}"></script>
    <script type = "text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
    <script type = "text/javascript" src="{%  static "js/scripts.js"%}"></script>
  </body>
</html>